#ifndef GRANTLEE_VERSION_H
#define GRANTLEE_VERSION_H
#define GRANTLEE_VERSION_MAJOR 5
#define GRANTLEE_VERSION_MINOR 2
#define GRANTLEE_VERSION_PATCH 0
#define GRANTLEE_VERSION_STRING "5.2.0"
#define GRANTLEE_VERSION ((5<<16)|(2<<8)|(0))
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "5.2"
#define GRANTLEE_MIN_PLUGIN_VERSION 0
#endif // GRANTLEE_VERSION_H
